In [2]:
import numpy as np

In [5]:
#21. Write a NumPy program to reverse an array (the first element becomes the last).
x = np.arange(1,5)
print("Original array:")
print(x)
print("reverse array:")
x = x[::-1]
print(x) 

Original array:
[1 2 3 4]
reverse array:
[4 3 2 1]


In [6]:
#22. Write a NumPy program to convert an data type into to a floating type.
def Q22():
    a = [1, 2, 3, 4]
    print("Original array")
    print(a)
    x = np.asfarray(a)
    print("Array converted to a float type:")
    print(x)
Q22()

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [8]:
#23. Write a NumPy program to convert a list array.
def Q23():
    lst = [1, 7, 0, 6, 2, 5, 6]
    arr = np.array(lst)
    print ("List: ", lst)
    print ("Array: ", arr)
Q23()

List:  [1, 7, 0, 6, 2, 5, 6]
Array:  [1 7 0 6 2 5 6]


In [9]:
#24. Write a NumPy program to get the element-wise remainder of an array of division.
x = np.arange(7)
print("original array:")
print(x)
print("element- wise remainder of division:")
print(np.remainder(x,5))

original array:
[0 1 2 3 4 5 6]
element- wise remainder of division:
[0 1 2 3 4 0 1]


In [10]:
#25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.
x = np.arange(20,50)
print("original array:")
print(x)
print("element- wise remainder of division:")
print(np.remainder(x,3))

original array:
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
element- wise remainder of division:
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
